### Find all Content
GET http://localhost:8080/api/content

### Get content by id
GET http://localhost:8080/api/content

### Create new Content
POST http://localhost:8080/api/content
Content-Type: application/json

{
    "id": 2,
    "title": "My Second Blog Post",
    "desc": "May the light guide you",
    "status": "IDEA",
    "contentType": "ARTICLE",
    "dateCreated": 
}